name: Screamer
version: '1.4-DEVBUILD'
main: io.github.growingunderthetree.screamer.Screamer
api-version: 1.17
load: STARTUP
description: A simple plugin for broadcasting messages and clear lag
commands:
  kit:
    description: Get 32 iron ingot and 16 wood
    usage: /kit
    permission: Screamer.admin
  broadcast:
    description: Broadcast your lovely messages to everyone
    usage: /broadcast
    permission: screamer.member
  shrink:
    description: shrink the user health
    usage: /shrink
    permission: screamer.admin
permissions:
  member:
    description: basic member permission
    default: not op
  admin:
    description: better permission
    default: op
