name: Simple-spigot-plugin
version: '${project.version}'
main: io.github.growingunderthetree.screamer.Screamer
api-version: 1.18.1
load: STARTUP
description: A simple plugin for broadcasting messages and clear lag
commands:
  sreefens:
    description: Get 32 iron ingot and 16 wood
    usage: /kit
    permission: Screamer.admin
    permission-message: You have no permission lmao
  broadcast:
    description: Broadcast your lovely messages to everyone
    usage: /broadcast
    permission: screamer.member
  look:
    description: Get gears
    usage: /look
    permission: screamer.admin
  pvpstart:
    description: Send a message to show that the pvp event started
    usage: /pvpstart
    permission: screamer.admin
  teryones:
    description: Give pvp gear to yourself
      usage: /teryones
      permission: screamer.admin
  debug:
    description: It does nothing but to test that whether this works or not
    usage: /debug
    permission: screamer.admin
    permission-message: you have no permission lolol
permissions:
  member:
    description: basic member permission
    default: not op
  admin:
    description: better permission
    default: op
